version: "3.9"
services:

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ${DB_FOLDER}:/data/db
    networks:
      - developers
    deploy:
      replicas: 1

networks:
  developers: